### ISSUE TITLE
Fight the DMCA?

### ISSUE THREAD

**Issue by jetersen** [crazy-max/ama#1]
Sucks about https://github.com/crazy-max/docker-jetbrains-license-server are you going to fight the DMCA? 😅

**Comment by crazy-max** [comment]
Yes the [counter procedure has been launched](https://github.com/github/dmca/commit/3e0a6b4ece009dcaca2871e0af109863c4c09ee9). It's just a matter of time ;)

GitHub _(Aug 23, 23:30 CEST)_ :

> Hi Maxime,
> 
> We've notified the copyright holder of your counter notice. If we do not receive notice that an action has been filed seeking a court order to restrain you within ten (10) business days, the repository will be re-enabled.
> 
> All best,
> 
> [private]

I have also notified JetBrains about this _(Aug 23, 23:17 CEST)_ :

> Hi Jetbrains,
> 
> I'm the developer of the Docker image of Jetbrains License Server (https://github.com/crazy-max/docker-jetbrains-license-server) and my repository hase been takedown by GitHub following your request (I think ?) and according to this DMCA notice : https://github.com/github/dmca/blob/master/2018/2018-08-22-Jetbrains-2.md.
> 
> I've read carefuly every statements involving this DMCA and none of them concern the content of the source code in my repository. I hope it's a result of mistake or misidentification.
> 
> Can you help me to look at this please ? This Docker image is used in some companies (including mine) and some people are concerned about this.
> 
> Thanks again!
> 
> Regards,
> 
> Maxime KILT

I have also checked [DMCA repository](https://github.com/github/dmca) on GitHub and retractations are common things : https://github.com/github/dmca/blob/master/2018/2018-07-11-Jetbrains-retraction.md

**Comment by crazy-max** [comment]
Some news from JetBrains _(Aug 27, 14:17 CEST)_ :

> Dear Maxime!
> 
> I am sorry that you have this problem. Sometimes we have to request GitHub to take down the repositories at GitHub which violates JetBrains' rights, and it might happen that your repository was mistakenly recognized as doing that. I am really sorry if it happened in spite you had no code infringing JetBrains' rights.
> 
> Do I understand right that you do not have any license server code in your repository? Thus, where do you get a license server for your Docker image? This could be a root of a mistake in detection the code as infringing JetBrains' right, and I have to check this before asking GitHub to reinstate your repository.
> 
> With best regards,
> [private]
> University Relations
> JetBrains

Me _(Aug 27, 14:30 CEST)_ :

> Hello Philip!
> 
> Yes indeed I do not have the license server code in my repository. This may be due to the URL to the license server binaries included in the Dockerfile when it was built?
> I have also checked DMCA repository on GitHub and retractations are common things : https://github.com/github/dmca/blob/master/2018/2018-07-11-Jetbrains-retraction.md
> 
> Thanks :)
> 
> Maxime KILT

**Comment by crazy-max** [comment]
JetBrains _(Aug 27, 14:43 CEST)_ :

> Hi Maxime,
> 
> thank you for your quick response. Regrettably, I can not view or download the sources from the URL you sent to me, because the website requires a registration there, and I am suspicious about safety of such registrations. Thus, I can not check what the "URL to the license server binaries included in the Dockerfile" is.
> 
> Could you please just copy and paste this URL in your next reply to me?
> 
>     "I have also checked DMCA repository on GitHub and retractations are common things"
> 
> You are right, misdetections happen, but they are definitely not common and quite rare. Comparing to number of repositories which contain infringing content, the number of misdetected repositories is very low.
> 
> Still, I am very sorry that even a signle misdetection may happen, and I will do my best to resolve the issue with your repository as soon as possible.
> 
> Thank you.
> 
> With best regards,
> [private]
> University Relations
> JetBrains

Me _(Aug 27, 14:47 CEST)_ :

> Philip,
> 
> I have uploaded the repository content as an attachment here ;) Sorry for the inconvenience!
> 
> Maxime KILT
> 
> Attachment(s)
> docker-jetbrains-license-server.zip

JetBrains _(Aug 27, 22:03 CEST)_ :

> Hi Maxime!
> 
> Thank you for sharing the code. I am sorry, but your case requires an extended review at this point.
> 
> As far as I understand your code, the license server binary and/or source code is not a part of your repository.
> However, could you please tell me whether do you know if the license server image which you pull for your docker container violates any of JetBrains' rights, to the best of your knowledge?
> 
> I appreciate if you clarify it. I am sorry that it's necessary to wait a bit more until the final resolution of the case.
> Thank you.
> 
> With best regards,
> [private]
> University Relations
> JetBrains

**Then the ticket has been removed by JetBrains....** :

![image](https://user-images.githubusercontent.com/1951866/44719649-39830580-aac4-11e8-8135-83743b72bc91.png)

![image](https://user-images.githubusercontent.com/1951866/44719655-4142aa00-aac4-11e8-989d-a3d94a5e5bb0.png)

So I open with the previous messages and add my response :

> My request (ID 1720001) has been removed by your services. I hope it's a mistake so I open a new one here...
> 
> Hi Philip,
> 
> Indeed the license server and/or source is not part of my repository at all.
> 
> For example this repository has a Dockerfile with the same link to your jetbrains license server binary in the Dockerfile : https://github.com/elgohr/cf-jetbrains-license-server and this repository has been retracted from DMCA a month ago for the same behaviour : https://github.com/github/dmca/blob/master/2018/2018-07-11-Jetbrains-retraction.md
> Maybe you could check who from JetBrains has retracted this repository and why ? This could help I think.
> 
> Concerning the Docker image, i don't think it's violates any of JetBrains' rights as it has to be built locally.
> 
> Do not hesitate if you have any questions.
> 
> Best regards,
> 
> Maxime KILT

**Comment by crazy-max** [comment]
JetBrains (_Aug 28, 16:24 CEST_)

> Hi Maxime,
> 
> We investigated the matter in details, and I just sent a reinstate request regarding your repository to GitHub. It may takes few hours before they satisfy the request. I am sorry again for the trouble. Regrettably, sometimes it's really hard to detect if a particular code is used for infringing rights or not, and this was exactly that case.
> 
> Please accept my apologizes. I am really sorry that sometimes we make mistakes.
> 
> I appreciate very much if you reply and confirm that everything is fine when the issue will be completely resolved.
> 
> With best regards,
> [private]
> University Relations
> JetBrains

Should be solved quickly :tada: :tada: :tada:

**Comment by crazy-max** [comment]
Me (_Aug 28, 16:34 CEST_) :

> Hi Philip,
> 
> I saw your email, thank you for your actions on this issue. Mistakes are human. The main thing is that everything is back and I don't hold it against your teams or your products that I particularly appreciate.
> 
> Best regards,
> 
> Maxime KILT
> 
> PS: I will close this ticket when my repository is opened again.

**Comment by jetersen** [comment]
Super awesome!
Sadly I don't see their retraction on the DMCA repo yet 😱

**Comment by crazy-max** [comment]
@casz I have sent an email to GitHub :

> Hi [private],
>
> I have a great news of JetBrains about this DMCA :
> 
>     Hi Maxime,
> 
>     We investigated the matter in details, and I just sent a reinstate request regarding your repository to GitHub. It may takes few hours before they satisfy the request. I am sorry again for the trouble. Regrettably, sometimes it's really hard to detect if a particular code is used for infringing rights or not, and this was exactly that case.
> 
>     Please accept my apologizes. I am really sorry that sometimes we make mistakes.
> 
>     I appreciate very much if you reply and confirm that everything is fine when the issue will be completely resolved.
> 
>     With best regards,
>     [private]
>     University Relations
>     JetBrains
> 
> Do you have received their reinstate request ? They said few hours but the repo is still locked.
> 
> Thanks for your reply!
> 
> Maxime KILT

**Comment by jetersen** [comment]
Lucky the docker image is still available on dockerhub we already spun up two new license servers using your docker image! Very much appreciated.

Updating from very old license servers that were hosted on windows and never maintained 😂
Build 10226 and 11073 😒

**Comment by crazy-max** [comment]
> Lucky the docker image is still available on dockerhub we already spun up two new license servers using your docker image!

Yes fortunately it would be more complicated otherwise!

> Very much appreciated.

You're welcome!

> Updating from very old license servers that were hosted on windows and never maintained joy
Build 10226 and 11073 :unamused:

I know the feeling, I have migrated many things to Docker :wink:

**Comment by jetersen** [comment]
Maybe they need a firmer hand 😅 This DMCA is not doing any favors for your repos discoverability 😭

**Comment by crazy-max** [comment]
@casz I have wrote to JetBrains again.

Me (_Aug 29, 16:34 CEST_) :

> Hi [private],
> 
> You said it could take few hours but the repo is still locked.
> Have you got some feedback of GitHub about this ?
> This DMCA is not doing any favors for my repo discoverability :(
> 
> Regards,
> 
> Maxime KILT

JetBrains (_Aug 29, 16:52 CEST_) :

> Hi Maxime,
> 
> I am sorry if I mis-made your expectations. GitHub may react fast, but sometimes it takes longer. I hoped for the best.
> 
> I'll remind them in few minutes about the issue, and I hope they can move it forward.
> 
> As far as I know GitHub policy, they definitely will reinstate your repository no later than Sep 7th. I know that it does not sound satisfactory for you, thus I am doing my best to make it happen as soon as possible. Regrettably, I can communicate with them via e-mail only, and I hope they will react as prompt as they can.
> 
> With best regards,
> [private]
> University Relations
> JetBrains

**Comment by crazy-max** [comment]
It's back : https://github.com/crazy-max/docker-jetbrains-license-server :tada: :tada: :tada:

**Comment by jetersen** [comment]
Congratulations, thank you for keeping me updated 🎊🎊🎊

**Comment by crazy-max** [comment]
About discoverability, yeah indeed..... :

![image](https://user-images.githubusercontent.com/1951866/44820968-86192e80-abf3-11e8-9fdf-457352e7b984.png)
