### ISSUE TITLE
Helpscout - Rocketchat Integration

### ISSUE THREAD

**Issue by franckadil** [crazy-max/ama#3]
The Help Scout + Rocket.Chat integration centralizes your team communications and turns conversation into action. Make the most of every action you take, so you can keep the focus on delighting your customer faster.

![image](https://user-images.githubusercontent.com/42721509/58262834-e8fab900-7d72-11e9-8921-c2c374283dcd.png)
_Example of a Help Scout conversation update in Rocket.Chat_

**Do more with Rocket.Chat and Help Scout**

- Instantly post Help Scout events to the Rocket.Chat channel of your choice.
- See notifications when a conversation is created, updated, replied or closed.

A better experience for your customers, fewer headaches for your team. You'll be set up in minutes with Rocket.Chat.

**Comment by crazy-max** [comment]
Can you add examples of JSON payloads and links to API doc please ? Thanks

**Comment by franckadil** [comment]
## Documentation

### WebHook
- [ Overview](https://developer.helpscout.com/webhooks/)
- [Conversation Object](https://developer.helpscout.com/webhooks/objects/conversation/)
- [Create Webhook](https://developer.helpscout.com/mailbox-api/endpoints/webhooks/create/)
- [Delete WebHook](https://developer.helpscout.com/mailbox-api/endpoints/webhooks/delete/)
- [Get Webhook](https://developer.helpscout.com/mailbox-api/endpoints/webhooks/get/)
- [List Webhook](https://developer.helpscout.com/mailbox-api/endpoints/webhooks/list/)
- [Update Webhook](https://developer.helpscout.com/mailbox-api/endpoints/webhooks/update/)

## Api 2.0
### Overview

[Mailbox API 2.0](https://developer.helpscout.com/mailbox-api/)

### Endpoints
[Get conversations](https://developer.helpscout.com/mailbox-api/endpoints/conversations/get/)
[List conversations](https://developer.helpscout.com/mailbox-api/endpoints/conversations/list/)

**Comment by crazy-max** [comment]
@franckadil Unfortunately, I wouldn't have time to help you. I advise you to create a post on the [RocketChat forum](https://forums.rocket.chat/c/rocket-chat-apps) for your request.
