### ISSUE TITLE
How are you looking for Telemetry?

### ISSUE THREAD

**Issue by Seithx** [crazy-max/ama#4]
Hi,

Just a general intreset question, since I'm going into "the field" maybe.

I tried downloading Wireshark, and did not find any Windows related services, which is good, means it works ;)

But just wanted to know a bit more on the subject, if you will.

Thanks :)

**Comment by crazy-max** [comment]
Hi @Seithx,

I assume you're talking about [WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker)? If so, I explain in the [README](https://github.com/crazy-max/WindowsSpyBlocker#telemetry-and-data-collection) how I gather telemetry data.
